# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'admin_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x64min_service.proto\x12\x0c\x61\x64minservice\"8\n\x11UserStatusRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t\"%\n\x12UserStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2e\n\x0c\x41\x64minService\x12U\n\x10UpdateUserStatus\x12\x1f.adminservice.UserStatusRequest\x1a .adminservice.UserStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSTATUSREQUEST']._serialized_start=37
  _globals['_USERSTATUSREQUEST']._serialized_end=93
  _globals['_USERSTATUSRESPONSE']._serialized_start=95
  _globals['_USERSTATUSRESPONSE']._serialized_end=132
  _globals['_ADMINSERVICE']._serialized_start=134
  _globals['_ADMINSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
