# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: discount_campaign.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'discount_campaign.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64iscount_campaign.proto\x12\x10\x64iscountcampaign\"\xb7\x01\n\x13\x43\x61mpaignSyncRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x0f\n\x07shop_id\x18\x02 \x01(\t\x12\x15\n\rcampaign_name\x18\x03 \x01(\t\x12\x15\n\rdiscount_type\x18\x04 \x01(\t\x12\x16\n\x0e\x64iscount_value\x18\x05 \x01(\x02\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\"\'\n\x14\x43\x61mpaignSyncResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x17\x44iscountCampaignService\x12]\n\x0cSyncCampaign\x12%.discountcampaign.CampaignSyncRequest\x1a&.discountcampaign.CampaignSyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discount_campaign_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMPAIGNSYNCREQUEST']._serialized_start=46
  _globals['_CAMPAIGNSYNCREQUEST']._serialized_end=229
  _globals['_CAMPAIGNSYNCRESPONSE']._serialized_start=231
  _globals['_CAMPAIGNSYNCRESPONSE']._serialized_end=270
  _globals['_DISCOUNTCAMPAIGNSERVICE']._serialized_start=272
  _globals['_DISCOUNTCAMPAIGNSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
