# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'session_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15session_service.proto\x12\x07session\"O\n\x12SessionSyncRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rsession_event\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"&\n\x13SessionSyncResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0eSessionService\x12H\n\x0bSyncSession\x12\x1b.session.SessionSyncRequest\x1a\x1c.session.SessionSyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONSYNCREQUEST']._serialized_start=34
  _globals['_SESSIONSYNCREQUEST']._serialized_end=113
  _globals['_SESSIONSYNCRESPONSE']._serialized_start=115
  _globals['_SESSIONSYNCRESPONSE']._serialized_end=153
  _globals['_SESSIONSERVICE']._serialized_start=155
  _globals['_SESSIONSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
